Added instructions for setting up dev env on Windows
pysmo/pysmo pull request #82
Opened 2023-06-27 09:02 UTC by Omkar-Ranadive

Added instructions to set up development environment on Windows under "Development Environment" part of the documentation.

2023-06-27 10:44 UTC, smlloyd commented on docs/source/developing.md
> +choco install pandoc
I think this would be better off in a subsection below "Requirements", because:
- Pandoc is also required on other platforms.
- Only needed to build the documentation, which should be mentioned.

Perhaps link to [https://pandoc.org/installing.html](url) and also add something like: "On Windows you can install it with choco install pandoc.

2023-06-27 10:45 UTC, smlloyd commented on docs/source/developing.md
> +* Once Chocolatey is installed, run the following commands to install the dependencies:
Tell users to do this in a command prompt (and does it have to run as administrator?)

2023-06-27 10:47 UTC, smlloyd commented on docs/source/developing.md
> +To set up the development environment correctly on Windows, we need a few additional steps.
I've been trying to use "we" for things that we (pysmo devs) do, and "you" for things the user should do. Let's try to be consistent with this (if I missed it somewhere feel free to edit it!).

2023-06-27 10:48 UTC, smlloyd commented on docs/source/developing.md
> +## Setting up the development environment on Windows
I think this would fit better as a (the first?) subsection below Requirements. Also could be shortened to "Setting up Windows".

2023-06-27 11:03 UTC, smlloyd requested changes
See inline comments

2023-07-10 06:12 UTC, Omkar-Ranadive commented
> See inline comments

Pushed a new commit with the requested changes

2023-08-01 13:39 UTC, merged